import Image from "next/image";
import ImageButton from "@/components/addboard/ImageButton";
import styles from "@/styles/addboard/CustomBoard.module.scss";

const CustomBoard = () => {
  return (
    <div>
      <div>
        <button>
          <Image
            src="/images/icon/ic_bold.svg"
            alt="bold"
            className={styles.searchImage}
            width={20}
            height={20}
          />
        </button>
        <button>
          <Image
            src="/images/icon/ic_italic.svg"
            alt="italic"
            className={styles.searchImage}
            width={20}
            height={20}
          />
        </button>
        <button>
          <Image
            src="/images/icon/ic_underline.svg"
            alt="under"
            className={styles.searchImage}
            width={20}
            height={20}
          />
        </button>
      </div>
      <div>
        <button>
          <Image
            src="/images/icon/ic_align.svg"
            alt="under"
            className={styles.searchImage}
            width={20}
            height={20}
          />
        </button>
        <button>
          <Image
            src="/images/icon/ic_align.svg"
            alt="under"
            className={styles.searchImage}
            width={20}
            height={20}
          />
        </button>
        <button>
          <Image
            src="/images/icon/ic_align.svg"
            alt="align"
            className={styles.searchImage}
            width={20}
            height={20}
          />
        </button>
      </div>
      <div>
        <button>
          <Image
            src="/images/icon/ic_bullet.svg"
            alt="align"
            className={styles.searchImage}
            width={20}
            height={20}
          />
        </button>
        <button>
          <Image
            src="/images/icon/ic_number.svg"
            alt="align"
            className={styles.searchImage}
            width={20}
            height={20}
          />
        </button>
        <button>
          <Image
            src="/images/icon/ic_color.svg"
            alt="align"
            className={styles.searchImage}
            width={20}
            height={20}
          />
        </button>
        <ImageButton />
      </div>
      <div>
        <button>
          <Image
            src="/images/icon/ic_link.svg"
            alt="align"
            className={styles.searchImage}
            width={20}
            height={20}
          />
        </button>
      </div>
    </div>
  );
};

export default CustomBoard;
